CREATE TYPE GUITAR_CATEGORY AS ENUM ('ELECTRIC', 'ACOUSTIC', 'CLASSICAL');

CREATE TABLE GUITAR_CATEGORY
(
    ID   INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE GUITAR_ITEM
(
    ID          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE       VARCHAR(255)   NOT NULL,
    DESCRIPTION TEXT,
    PRICE       DECIMAL(10, 2) NOT NULL,
    BODY        VARCHAR(100)   NOT NULL,
    NECK        VARCHAR(100)   NOT NULL,
    PICKUPS     VARCHAR(100),
    CATEGORY_ID INT            NOT NULL,
    IMAGE_URL   VARCHAR(500)
);

CREATE TYPE PAYMENT_TYPE AS ENUM ('PAYPAL', 'ON_DELIVERY');

CREATE TABLE USER_PURCHASE
(
    ID        INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    QUANTITY  INT          NOT NULL,
    TOTAL_PRICE DOUBLE NOT NULL,
    USER_ID   INT          NOT NULL,
    GUITAR_ID INT          NOT NULL,
    DATE      DATE         NOT NULL,
    PAYMENT   PAYMENT_TYPE NOT NULL
);

CREATE TYPE USER_ROLE AS ENUM ('REGULAR', 'ADMIN');

CREATE TABLE USERS
(
    ID       INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255)        NOT NULL,
    EMAIL    VARCHAR(255) UNIQUE NOT NULL,
    ROLE     USER_ROLE           NOT NULL
);

CREATE TABLE USER_LOGIN
(
    ID         INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID    INT          NOT NULL,
    DATE       DATE         NOT NULL,
    IP_ADDRESS VARCHAR(255) NOT NULL
);


