CREATE TYPE GUITAR_CATEGORY AS ENUM ('ELECTRIC', 'ACOUSTIC', 'CLASSICAL');

CREATE TABLE GUITAR_ITEM
(
    ID          INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE       VARCHAR(255)   NOT NULL,
    DESCRIPTION TEXT,
    PRICE       DECIMAL(10, 2) NOT NULL,
    BODY        VARCHAR(100)    NOT NULL,
    NECK        VARCHAR(100)    NOT NULL,
    PICKUPS     VARCHAR(100),
    CATEGORY    GUITAR_CATEGORY    NOT NULL,
    IMAGE_URL   VARCHAR(500)
);


